### ISSUE TITLE
Membuat UI Main Activity

### ISSUE THREAD

**Issue by amirisback** [amirisback/eudeka-final-project-group4#10]
Main Activity Terdiri dari FrameLayout Dan Bottom Navigation, untuk UI tinggal buat XMLnya saja

**Comment by AjiSetya** [comment]
untuk BottomNavigation itu pakai ViewPager kah? apa engga panggil2 frgment aja kaya biasa mas? jadi cuma sediain komponen container kaya FrameLayout

**Comment by amirisback** [comment]
kalo mas aji bisanya seperti itu gpp mas, kalo mau pake viewpager juga masalah, tinggal saling komunikasi aja

**Comment by AjiSetya** [comment]
oke mas, saya pakai FrameLayout saja..

**Comment by amirisback** [comment]
Okey siapp

**Comment by amirisback** [comment]
Untuk Referensi yang viewpager + bottom navigation bisa di lihat disini :

https://github.com/amirisback/MADE-Amirisback-CatalogueMovie/blob/master/app/src/main/java/id/frogobox/cataloguemovie/views/activities/MainActivity.java
